### PR TITLE
Issue #178: Split up known issues

### PR DESCRIPTION
**Pull request by pieter-edelman-nictiz**
Split up known issues in a "deliberate deviations from the guidelines" part and a more "ephemeral" part, due to tooling errors etc.

In addition, implement some changes in the tools to handle calculating effective cardinalities better.

### CODE REVIEW

**Comment by pieter-edelman-nictiz** [comment]
Graag even jullie blik om te kijken of jullie het eens zijn met de wijzigingen in known-issues en in de profielen.

NB. alle verplichte vinkjes in deze pull request staan eindelijk op groen :) Er is nog wel het rode vinkje van de "strengere" handmatige test, maar dat is in dit geval loos alarm.

**Review by ArdonToonstra — APPROVED** [review]
Nice! 
I like the way the file is now split up. 
I do not completely understand the new syntax yet with regards to the wildcard '*' but it works so for now I think I can approve the PR.
Perhaps bonus points can be won by having a bit of documentation (maybe in the README on the root folder)?

**Comment by pieter-edelman-nictiz** [comment]
> Nice! I like the way the file is now split up. I do not completely understand the new syntax yet with regards to the wildcard '*' but it works so for now I think I can approve the PR. Perhaps bonus points can be won by having a bit of documentation (maybe in the README on the root folder)?

That's a good suggesion, I'll add some documentation.

**Comment by pieter-edelman-nictiz** [comment]
> > Nice! I like the way the file is now split up. I do not completely understand the new syntax yet with regards to the wildcard '*' but it works so for now I think I can approve the PR. Perhaps bonus points can be won by having a bit of documentation (maybe in the README on the root folder)?
> 
> That's a good suggesion, I'll add some documentation.

I think I'll track back from this statement. At the moment, proper documentation of known issues _in general_ is missing so I'll create a task for this. The wildcard syntax is described in the repo's for the tools that are used.

**Pull request merged**
