### PR TITLE
ext-PeriodOfUse

### PR DESCRIPTION
**Pull request by pieter-edelman-nictiz**
I don't think I'm in favor of the way this is defined now. It would make more sense to me to generalize these extensions as implementations of zib TimeInterval (thus ext-TimeInterval.startDateTime-endDateTime and ext-TimeInterval.Duration). They can be needed to the profiles based on the need.

The description and purpose, as well as the mappings, should be adjusted accordingly. I think the mappings to the specific zibs should be removed _anyways_ and added from the hosting profiles, otherwise the mappings end up in profiles where it is not relevant.

### CODE REVIEW

**Comment by ArdonToonstra** [comment]
Do you mean to use two DataTimes rather than a Period for ext-TimeInterval.startDateTime-endDateTime? That would have implications for searching on this element.
The PeriodOfUse concepts plays an important role for searching. Perhaps we can make it one complex extension (ext-TimeInterval), and we can make the SearchParameter take duration into account using FHIRpath? It is possible to add and subtract dates etc: http://hl7.org/fhirpath/N1/#datetime-arithmetic 

Not sure if I completely agree with this:

>I think the mappings to the specific zibs should be removed anyways and added from the hosting profiles, otherwise the mappings end up in profiles where it is not relevant.

The mappings from the other profiles will end up in the host profile without a mapping declaration. It will help the implementer to recognize that the concept/extension is used in different profiles the same manner. But I agree that the mapping should move to the host profile if the extension is generalized.

**Comment by ArdonToonstra** [comment]
I reworked the profiles somewhat. Merged the two extension profiles into one. Let's discuss this Monday.

**Comment by pieter-edelman-nictiz** [comment]
> Do you mean to use two DataTimes rather than a Period for ext-TimeInterval.startDateTime-endDateTime? That would have implications for searching on this element.

No, I just mean that this should be a general (set of) extension(s) implementing zib TimeInterval rather than extensions than a single set for a lot of concepts (but not more) that use this zib. I don't see why we should treat this situation in a special way actually.

**Comment by pieter-edelman-nictiz** [comment]
> The mappings from the other profiles will end up in the host profile without a mapping declaration. It will help the implementer to recognize that the concept/extension is used in different profiles the same manner. But I agree that the mapping should move to the host profile if the extension is generalized.

The implementer should recognize the concept as zib TimeInterval IMO.

**Comment by ArdonToonstra** [comment]
>No, I just mean that this should be a general (set of) extension(s) implementing zib TimeInterval rather than extensions than a single set for a lot of concepts (but not more) that use this zib. I don't see why we should treat this situation in a special way actually

We tried that be making a datatype profile on Period. I am not sure if you can extract enough meaning out of a generic zib-TimerInterval extension in the host profile to know that it is used for the PeriodOfUse concept.

**Comment by ArdonToonstra** [comment]
Mmm, I just realized why the concepts were split in two extensions in the first... sometimes there is a native FHIR element available...

**Pull request closed without merging**
